http:
  middlewares:
    simpleAuth:
      basicAuth:
        users:
          - '$secret'
  routers:
    api:
      rule: Host(`$TRAEFIK_DOMAIN`)
      entrypoints:
        - websecure
      middlewares:
        - simpleAuth
      service: api@internal
      tls:
        certResolver: lets-encrypt

