version: '3'
name: base

services:
  traefik:
    container_name: traefik
    restart: unless-stopped
    image: traefik:latest
    networks:
      - traefiknet
    ports:
      - 80:80
      - 443:443
      - 8883:8883
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml
      - ./traefik/traefik_api.yml:/traefik_api.yml
      - ./traefik/acme.json:/cert/acme.json

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    expose:
      - 9000
    networks:
      - traefiknet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.$domain`)
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=lets-encrypt
      - traefik.http.services.portainer.loadbalancer.server.port=9000

networks:
  traefiknet:
    external: true

