entryPoints:
  traefiknet:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
api:
  dashboard: true
certificatesResolvers:
  lets-encrypt:
    acme:
      email: $email
      storage: acme.json
      tlsChallenge: {}
providers:
  docker:
    watch: true
    network: traefiknet
  file:
    filename: traefik_api.yml

